//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Degausser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Degausser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GuitarChords {
            get {
                object obj = ResourceManager.GetObject("GuitarChords", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Instruments&gt;
        ///  &lt;Instrument ID=&quot;0&quot; Name=&quot;(Blank)&quot; Type=&quot;NUL&quot; Midi=&quot;255&quot;/&gt;
        ///  
        ///  &lt;!-- SCL Instruments --&gt;
        ///  &lt;Instrument ID=&quot;1&quot; Name=&quot;Piano&quot; Type=&quot;SCL&quot; Midi=&quot;1&quot;/&gt;
        ///  &lt;Instrument ID=&quot;2&quot; Name=&quot;Electric Piano&quot; Type=&quot;SCL&quot; Midi=&quot;3&quot;/&gt;
        ///  &lt;Instrument ID=&quot;3&quot; Name=&quot;Rock Organ&quot; Type=&quot;SCL&quot; Midi=&quot;18&quot;/&gt;
        ///  &lt;Instrument ID=&quot;4&quot; Name=&quot;Synth Lead&quot; Type=&quot;SCL&quot; Midi=&quot;81&quot;/&gt;
        ///  &lt;Instrument ID=&quot;5&quot; Name=&quot;Synth Bell&quot; Type=&quot;SCL&quot; Midi=&quot;88&quot;/&gt;
        ///  &lt;Instrument ID=&quot;6&quot; Name=&quot;Pipe Organ&quot; Type=&quot;SCL&quot; M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Instruments {
            get {
                return ResourceManager.GetString("Instruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PianoChords {
            get {
                object obj = ResourceManager.GetObject("PianoChords", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
